/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Icon, } from "./components/icon/icon";
export namespace Components {
    interface GclAlert {
        /**
          * The description of the message
         */
        "description": string;
        /**
          * The icon of the alert
         */
        "icon": Icon;
        /**
          * The message of the alert
         */
        "message": string;
        /**
          * Whether to show the icon
         */
        "showIcon": boolean;
        /**
          * The type of the alert
         */
        "type": "info" | "success" | "warning" | "error";
    }
    interface GclIcon {
        /**
          * The color of the icon.
         */
        "color"?: string;
        /**
          * Specifies which icon to use from the built-in set of icons.
         */
        "name"?: string;
        /**
          * Specifies whether the icon should horizontally flip when `dir` is `"rtl"`.
         */
        "rtl"?: boolean;
        /**
          * The size of the icon. Available options are: `"small"` and `"large"`.
         */
        "size"?: string;
    }
}
declare global {
    interface HTMLGclAlertElement extends Components.GclAlert, HTMLStencilElement {
    }
    var HTMLGclAlertElement: {
        prototype: HTMLGclAlertElement;
        new (): HTMLGclAlertElement;
    };
    interface HTMLGclIconElement extends Components.GclIcon, HTMLStencilElement {
    }
    var HTMLGclIconElement: {
        prototype: HTMLGclIconElement;
        new (): HTMLGclIconElement;
    };
    interface HTMLElementTagNameMap {
        "gcl-alert": HTMLGclAlertElement;
        "gcl-icon": HTMLGclIconElement;
    }
}
declare namespace LocalJSX {
    interface GclAlert {
        /**
          * The description of the message
         */
        "description"?: string;
        /**
          * The icon of the alert
         */
        "icon"?: Icon;
        /**
          * The message of the alert
         */
        "message"?: string;
        /**
          * Whether to show the icon
         */
        "showIcon"?: boolean;
        /**
          * The type of the alert
         */
        "type"?: "info" | "success" | "warning" | "error";
    }
    interface GclIcon {
        /**
          * The color of the icon.
         */
        "color"?: string;
        /**
          * Specifies which icon to use from the built-in set of icons.
         */
        "name"?: string;
        /**
          * Specifies whether the icon should horizontally flip when `dir` is `"rtl"`.
         */
        "rtl"?: boolean;
        /**
          * The size of the icon. Available options are: `"small"` and `"large"`.
         */
        "size"?: string;
    }
    interface IntrinsicElements {
        "gcl-alert": GclAlert;
        "gcl-icon": GclIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gcl-alert": LocalJSX.GclAlert & JSXBase.HTMLAttributes<HTMLGclAlertElement>;
            "gcl-icon": LocalJSX.GclIcon & JSXBase.HTMLAttributes<HTMLGclIconElement>;
        }
    }
}
